language: rust
rust:
  - stable
  - beta
  - nightly
dist: trusty

addons:
  apt:
    packages:
      - libssl-dev

cache:
  cargo: true
  directories:
    - $HOME/.src

env:
  global:
    - MDBOOK_VERSION=0.2.1
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - cargo clean
  - cargo build
  - cargo test
  - mdbook build

after_success:
  - ./.travis/after_success.sh

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: book
  github-token: $GH_DEPLOY_TOKEN
  on:
    branch: master
