[package]
name = "vellum"
version = "0.1.0"
authors = ["Lina Cambridge <lina@mozilla.com>"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4"
lazy_static = "1.1.0"

[dev-dependencies]
env_logger = "0.5.12"
